version: "3.9"
services:
  core:
    build:
      context: .
      dockerfile: ./py3/Dockerfile
    ulimits:
      memlock: -1
    restart: always
    tty: true
    volumes:
      - ./src:/src

    #GPUを使う場合の設定
    environment:
      - "NVIDIA_VISIBLE_DEVICES=all"
      - "NVIDIA_DRIVER_CAPABILITIES=all"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [ gpu ]
